nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/eumel8/otc-rds-operator
  pullPolicy: IfNotPresent
#  tag: latest

env: production

logLevel: info

numWorkers: 4

ha:
  enabled: true
  leaderElection:
    leaseDurationSeconds: 15
    renewDeadlineSeconds: 10
    retryPeriodSeconds: 2
  replicaCount: 3

# addEnv:
#   OS_DEBUG: 1

otc: {}
# otc:
#   auth_url: https://iam.eu-de.otc.t-systems.com:443/v3
#   api_version: "3"
#   region: eu-de
#   project_name: eu-de
#   domain_name: OTC-EU-DE-000000000010000000001
#   username: user
#   password: password

monitoring:
  enabled: true
  path: /metrics
  port: 2112
  namespace: cattle-monitoring-system
  interval: 10s
  labels:
    release: monitoring

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 512Mi

securityContext:
  allowPrivilegeEscalation: false
  capabilities: {}
  privileged: false
  runAsNonRoot: true
  runAsUser: 1000

nodeSelector: {}
