{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/NetworkPolicy" }}
{{ $fullName := include "otc-rds-operator.fullname" . }}
{{ $selectorLabels := include "otc-rds-operator.selectorLabels" . }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
  name: {{ $fullName }}
spec:
  egress:
  - ports:
    - port: 3306
      protocol: TCP
  - ports:
    - port: 5432
      protocol: TCP
  - ports:
    - port: 53
      protocol: TCP
  - ports:
    - port: 53
      protocol: UDP
  podSelector:
    matchLabels:
      {{- $selectorLabels  | nindent 6 }}
  policyTypes:
  - Egress
{{- end }}
