{{ $fullName := include "otc-rds-operator.fullname" . }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "otc-rds-operator.labels" . | nindent 4 }}
data:
  OS_PROJECT_NAME: {{ .Values.otc.project_name | default "eu-de" }}
  OS_REGION_NAME: {{ .Values.otc.region_name | default "eu-de" }}
  OS_AUTH_URL: {{ .Values.otc.auth_url | default "https://iam.eu-de.otc.t-systems.com:443/v3" }}
  OS_IDENTITY_API_VERSION: {{ .Values.otc.api_version | default 3 }}
  OS_USER_DOMAIN_NAME: {{ .Values.otc.domain_name }}
  OS_USERNAME: {{ .Values.otc.username }}
  OS_PASSWORD: {{ .Values.otc.password }}
