{{- if .Values.otc}}
{{ $fullName := include "otc-rds-operator.fullname" . }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "otc-rds-operator.labels" . | nindent 4 }}
data:
  OS_PROJECT_NAME: {{ .Values.otc.project_name | default "eu-de" | b64enc | quote }}
  OS_PROJECT_ID: {{ .Values.otc.project_id | default "7c3ec0b3db5f476990043258670caf82" | b64enc | quote }}
  OS_REGION_NAME: {{ .Values.otc.region_name | default "eu-de" | b64enc | quote }}
  OS_AUTH_URL: {{ .Values.otc.auth_url | default "https://iam.eu-de.otc.t-systems.com:443/v3" | b64enc | quote }}
  OS_IDENTITY_API_VERSION: {{ .Values.otc.api_version | default "3" | b64enc | quote }}
  OS_USER_DOMAIN_NAME: {{ .Values.otc.domain_name | b64enc | quote }}
  OS_USERNAME: {{ .Values.otc.username | b64enc | quote }}
  OS_PASSWORD: {{ .Values.otc.password | b64enc | quote }}
{{- end }}
