// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// RdsListerExpansion allows custom methods to be added to
// RdsLister.
type RdsListerExpansion interface{}

// RdsNamespaceListerExpansion allows custom methods to be added to
// RdsNamespaceLister.
type RdsNamespaceListerExpansion interface{}
