apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rdss.otc.mcsps.de
spec:
  group: otc.mcsps.de
  names:
    kind: Rds
    listKind: RdsList
    plural: rdss
    singular: rds
    shortNames:
      - rds
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: object
          properties:
            spec:
              type: object
              properties:
                datastoretype:
                  type: string
                datastoreversion:
                  type: string
                volumetype:
                  type: string
                volumesize:
                  type: integer
                  minimum: 40
                hamode:
                  type: string
                hareplicationmode:
                  type: string
                port:
                  type: string
                password:
                  type: string
                backuprestoretime:
                  type: string
                backupstarttime:
                  type: string
                backupkeepdays:
                  type: integer
                flavorref:
                  type: string
                reboot:
                  type: boolean
                region:
                  type: string
                availabilityzone:
                  type: string
                vpc:
                  type: string
                subnet:
                  type: string
                securitygroup:
                  type: string
              required:
                - datastoretype
                - datastoreversion
                - volumetype
                - volumesize
                - hamode
                - hareplicationmode
                - port
                - password
                - backupstarttime
                - backupkeepdays
                - flavorref
                - region
                - availabilityzone
                - vpc
                - subnet
                - securitygroup
            status:
              type: object
              properties:
                events:
                  type: string
                id:
                  type: string
                ip:
                  type: string
                status:
                  type: string
