{{ if .Values.rbac.master.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rdsoperator-view
  labels:
    {{- include "otc-rds-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - otc.mcsps.de
    resources:
      - rdss
    verbs:
      - get
      - list
      - watch
{{ end }}
