{{ if .Values.rbac.master.enabled }}
{{ $fullName := include "otc-rds-operator.fullname" . }}
{{ $fullNameOps := print (include "otc-rds-operator.fullname" .) "-ops" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rdsoperator
  labels:
    {{- include "otc-rds-operator.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - otc.mcsps.de
    resources:
      - rdss
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - patch
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - update
    - get
    - list
    - patch
    - watch
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    verbs:
    - create
    - delete
    - update
    - get
{{ end }}
