{{ if .Values.rbac.user.enabled }}
{{ $fullName := include "otc-rds-operator.fullname" . }}
{{ $fullNameUser := print (include "otc-rds-operator.fullname" .) }}
{{- $ns1 := (splitList " " .Values.watchNamespaces ) }}
{{- $ns2 := (splitList " " .Values.watchNamespaces | reverse) }}
{{- range $s1 := $ns1 }}
{{- range $s2 := $ns2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullNameUser }} "-" {{ $s2 }}
  namespace: {{ $s1 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullNameUser }} "-" {{ $s2 }}
subjects:
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io

{{ end }}
{{ end }}
{{ end }}
