{{ if .Values.rbac.user.enabled }}
{{ $fullNameUser := print (include "otc-rds-operator.fullname" .) "-user" }}
{{- $ns1 := (splitList " " .Values.watchNamespaces ) }}
{{- range $s1 := $ns1 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullNameUser }}
  namespace: {{ $s1 }}
rules:
  - apiGroups:
      - otc.mcsps.de
    resources:
      - rdss
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
{{ end }}
{{ end }}
