{{ $fullNameLease := print (include "otc-rds-operator.fullname" .) "-lease" }}
{{ $fullName := include "otc-rds-operator.fullname" . }}
{{ if .Values.ha.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullNameLease }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullNameLease }}
subjects:
  - kind: ServiceAccount
    name: {{ $fullName }}
{{ end }}
