{{ $fullNameLease := print (include "otc-rds-operator.fullname" .) "-lease" }}
{{ if .Values.ha.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullNameLease }}
  labels:
    {{- include "otc-rds-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - watch
      - create
      - update
{{ end }}
