{{ $fullName := include "otc-rds-operator.fullname" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "otc-rds-operator.labels" . | nindent 4 }}
