name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
      
permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint
        run: make lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Bin
        uses: actions/upload-artifact@v2
        with:
          name: otc-rds-operator
          path: ./bin/otc-rds-operator

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: make cover

      - name: Cover
        uses: actions/upload-artifact@v2
        with:
          name: cover
          path: ./cover.html
