# https://github.com/marketplace/actions/kubectl-helm
on:
  push:
    paths:
      - chart/**

name: helmtest
jobs:
  deploy:
    name: helmtest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: helm lint
      uses: wahyd4/kubectl-helm-action@master
      with:
        args: |
          helm lint chart/    
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
    - name: helm template
      uses: wahyd4/kubectl-helm-action@master
      with:
        args: |
          helm template chart/
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
    - name: helm unittest
      uses: wahyd4/kubectl-helm-action@master
      with:
        args: |
          helm plugin install https://github.com/quintush/helm-unittest
          helm unittest chart/    
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
